version: 0.2

files:
  - source: /
    destination: /home/ec2-user/web/
    overwrite: purge
    file_exists_behavior: OVERWRITE

env:
  variables:
    AWS_ACCOUNT_ID: 536697261588
    ECR_IMAGE_REGION: ap-southeast-1

phases:
  pre_build:
    commands:
      - echo "1. Pre build step"
      - aws ecr get-login-password --region $ECR_IMAGE_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$ECR_IMAGE_REGION.amazonaws.com
  build:
    commands:
      - echo "2. Build step"
      - docker build -f ./deploy-helper/nginx/Dockerfile.nginx -t nginx .
      - docker build -f Dockerfile -t php-fpm .
  post_build:
    commands:
      - echo 3. "Post build"
      - echo "3.1 Push built-nginx to ECR ---------"
      - docker tag built-nginx:latest $AWS_ACCOUNT_ID.dkr.ecr.$ECR_IMAGE_REGION.amazonaws.com/duyvd/built-nginx:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$ECR_IMAGE_REGION.amazonaws.com/duyvd/built-nginx:latest
      - echo "3.2 Push php-fpm to ECR --------"      
      - docker tag php-fpm:latest $AWS_ACCOUNT_ID.dkr.ecr.$ECR_IMAGE_REGION.amazonaws.com/duyvd/php-fpm:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$ECR_IMAGE_REGION.amazonaws.com/duyvd/php-fpm:latest
      - echo "3.3 Create image definitions --------"
      - printf "[{\"name\":\"php-fpm\",\"imageUri\":\"$AWS_ACCOUNT_ID.dkr.ecr.$ECR_IMAGE_REGION.amazonaws.com/php-fpm:latest\"}," >> imagedefinitions.json
      - printf "{\"name\":\"nginx\",\"imageUri\":\"$AWS_ACCOUNT_ID.dkr.ecr.$ECR_IMAGE_REGION.amazonaws.com/built-nginx:latest\"}]" >> imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - README.md
    - imagedefinitions.json
